---
<%
# If you want to test the SSL certs, please create a .ssl.yml file with
# some valid settings for an s3 bucket, cert and key. 
# TODO: let's fix this to be mockable. 
if File.exist?('.ssl.yml')
  ssl = YAML.load_file('.ssl.yml')
else
  ssl = {}
end
%>

driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: setup
    run_list:
      - recipe[looker::setup]
    attributes:
  - name: user
    run_list:
      - recipe[looker::user]
    attributes:
  - name: ssl
    run_list:
      - recipe[looker::ssl]
    attributes:
      looker:
        ssl: 
          aws_access_key_id: <%= ssl['aws_access_key_id'] %>
          aws_secret_access_key: <%= ssl['aws_secret_access_key'] %>
          s3_bucket: <%= ssl['s3_bucket'] %>
          certificate_key_path: <%= ssl['certificate_key_path'] %>
          certificate_path: <%= ssl['certificate_path']%>