---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12

<% s3 = YAML.load_file('.s3.yml') %>

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: setup
    run_list:
      - recipe[looker::setup]
    attributes:
  - name: user
    run_list:
      - recipe[looker::user]
    attributes:
  - name: ssl
    run_list:
      - recipe[looker::ssl]
    attributes:
      - looker:
        ssl: 
          aws_access_key_id: <%= s3['aws_access_key_id'] %>
          aws_secret_access_key: <%= s3['aws_secret_access_key'] %>
          s3_bucket: <%= s3['s3_bucket'] %>
          certificate_key_path: <%= s3['certificate_key_path'] %>
          certificate_path: <%= s3['certificate_path']%>